name: flake_uuid
description: >
  Flake UUID provides 64- and 128-bit, k-ordered identifiers, which
  preserve their order of creation (somewhat) if sorted lexically.
version: 0.1.3
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/flake_uuid

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
